export default {
  
    cancel:require("../assets/images/cancel.png"),
    dp1: require("../assets/images/myntralogo.jpg"),
    dp2: require("../assets/images/check.jpg"),
    dp3: require("../assets/images/check1.jpg"),
    dp4: require("../assets/images/check2.jpg"),
    dp5: require("../assets/images/check3.jpg"),
    dp6: require("../assets/images/check4.jpg"),
    dp7: require("../assets/images/check5.jpg"),
    dp8: require("../assets/images/check6.jpg"),
    dp9: require("../assets/images/check7.jpg"),
    dp10: require("../assets/images/check8.jpg"),
    r1: require("../assets/images/round1.png"),
    r2: require("../assets/images/round2.jpg"),
    r3: require("../assets/images/round3.jpg"),
    r4: require("../assets/images/round4.jpg"),
    r5: require("../assets/images/round5.jpg"),
    r6: require("../assets/images/round6.jpg"),
    r7: require("../assets/images/round7.jpg"),
    m1: require("../assets/images/menu.png"),
    m2: require("../assets/images/search.png"),
    m3: require("../assets/images/alarm.png"),
    m4: require("../assets/images/heart.png"),
    m5: require("../assets/images/briefcase.png"),
    w1: require("../assets/images/w1.jpg"),
    profile: require("../assets/images/profile.png"),
    camera: require("../assets/images/camera.png"),
    gallery: require("../assets/images/gallery.png"),
  };